version: 0.2

phases:
  build:
    commands:
      - echo entered build phase via maven
      -  mvn clean package
  post_build:
    commands:
      - echo Build Completed Succesfully !!!
artifacts:
  files:
    - target/swift-gpi-bav:1.0.1
  discard-paths: yes
